import { Injectable } from '@nestjs/common';
import type { AIProvider } from './ai-provider.interface';
import type {
  AIResponse,
  ChatRequest,
  EmbeddingRequest,
  ImageRequest,
  ModerationRequest,
} from './ai-response';

const PRODUCT_ANALYSIS = {
  productName: 'Sample Product',
  brand: 'FakeBrand',
  category: 'General',
  subcategory: 'Demo',
  tags: ['fake'],
  description: 'Generated by FakeAIProvider',
  confidence: 0.91,
};

@Injectable()
export class FakeAIProvider implements AIProvider {
  async chat(_request: ChatRequest): Promise<AIResponse> {
    return {
      content: 'ok',
      raw: { driver: 'fake', method: 'chat' },
      tokensInput: 8,
      tokensOutput: 2,
    };
  }

  async analyzeImage(_request: ImageRequest): Promise<AIResponse> {
    return {
      content: { ...PRODUCT_ANALYSIS },
      raw: { driver: 'fake', method: 'analyzeImage' },
      tokensInput: 120,
      tokensOutput: 40,
    };
  }

  async embeddings(_request: EmbeddingRequest): Promise<AIResponse> {
    return {
      content: [0.1, 0.2, 0.3],
      raw: { driver: 'fake', method: 'embeddings' },
      tokensInput: 4,
      tokensOutput: 0,
    };
  }

  async moderation(_request: ModerationRequest): Promise<AIResponse> {
    return {
      content: { flagged: false },
      raw: { driver: 'fake', method: 'moderation' },
      tokensInput: 4,
      tokensOutput: 0,
    };
  }
}
