import { Injectable } from '@nestjs/common';
import type { AIProvider } from './ai-provider.interface';
import { ProviderTimeoutError } from './provider-timeout';
import type {
  AIResponse,
  ChatRequest,
  EmbeddingRequest,
  ImageRequest,
  ModerationRequest,
} from './ai-response';

/** Frozen PRODUCT_ANALYSIS shape — keep in sync with ProductAnalysisOutput. */
export const FAKE_PRODUCT_ANALYSIS_OUTPUT = {
  productName: 'Sample Product',
  brand: 'FakeBrand',
  category: 'General',
  subcategory: 'Demo',
  tags: ['fake'],
  description: 'Generated by FakeAIProvider',
  confidence: 0.91,
};

@Injectable()
export class FakeAIProvider implements AIProvider {
  private analyzeImageContent: unknown | undefined;
  private failNextAnalyzeImageWithTimeout = false;

  setAnalyzeImageContent(content: unknown | undefined) {
    this.analyzeImageContent = content;
  }

  failNextWithTimeout() {
    this.failNextAnalyzeImageWithTimeout = true;
  }

  async chat(_request: ChatRequest): Promise<AIResponse> {
    return {
      content: 'ok',
      raw: { driver: 'fake', method: 'chat' },
      tokensInput: 8,
      tokensOutput: 2,
    };
  }

  async analyzeImage(_request: ImageRequest): Promise<AIResponse> {
    if (this.failNextAnalyzeImageWithTimeout) {
      this.failNextAnalyzeImageWithTimeout = false;
      throw new ProviderTimeoutError(60_000);
    }
    const content = this.analyzeImageContent ?? FAKE_PRODUCT_ANALYSIS_OUTPUT;
    this.analyzeImageContent = undefined;
    return {
      content,
      raw: { driver: 'fake', method: 'analyzeImage', content },
      tokensInput: 120,
      tokensOutput: 40,
    };
  }

  async embeddings(_request: EmbeddingRequest): Promise<AIResponse> {
    return {
      content: [0.1, 0.2, 0.3],
      raw: { driver: 'fake', method: 'embeddings' },
      tokensInput: 4,
      tokensOutput: 0,
    };
  }

  async moderation(_request: ModerationRequest): Promise<AIResponse> {
    return {
      content: { flagged: false },
      raw: { driver: 'fake', method: 'moderation' },
      tokensInput: 4,
      tokensOutput: 0,
    };
  }
}
