import { Injectable } from '@nestjs/common';
import type { AIProvider } from './ai-provider.interface';
import { ProviderTimeoutError } from './provider-timeout';
import type { AIResponse } from './ai-response';

/** Frozen PRODUCT_ANALYSIS shape — keep in sync with ProductAnalysisOutput. */
export const FAKE_PRODUCT_ANALYSIS_OUTPUT = {
  productName: 'Sample Product',
  brand: 'FakeBrand',
  category: 'General',
  subcategory: 'Demo',
  tags: ['fake'],
  description: 'Generated by FakeAIProvider',
  confidence: 0.91,
};

@Injectable()
export class FakeAIProvider implements AIProvider {
  private analyzeImageContent: unknown;
  private remainingTimeoutFailures = 0;

  setAnalyzeImageContent(content: unknown) {
    this.analyzeImageContent = content;
  }

  failNextWithTimeout() {
    this.remainingTimeoutFailures = 1;
  }

  failNextTimesWithTimeout(times: number) {
    this.remainingTimeoutFailures = times;
  }

  chat(): Promise<AIResponse> {
    return Promise.resolve({
      content: 'ok',
      raw: { driver: 'fake', method: 'chat' },
      tokensInput: 8,
      tokensOutput: 2,
    });
  }

  analyzeImage(): Promise<AIResponse> {
    if (this.remainingTimeoutFailures > 0) {
      this.remainingTimeoutFailures -= 1;
      return Promise.reject(new ProviderTimeoutError(60_000));
    }
    const content = this.analyzeImageContent ?? FAKE_PRODUCT_ANALYSIS_OUTPUT;
    this.analyzeImageContent = undefined;
    return Promise.resolve({
      content,
      raw: { driver: 'fake', method: 'analyzeImage', content },
      tokensInput: 120,
      tokensOutput: 40,
    });
  }

  embeddings(): Promise<AIResponse> {
    return Promise.resolve({
      content: [0.1, 0.2, 0.3],
      raw: { driver: 'fake', method: 'embeddings' },
      tokensInput: 4,
      tokensOutput: 0,
    });
  }

  moderation(): Promise<AIResponse> {
    return Promise.resolve({
      content: { flagged: false },
      raw: { driver: 'fake', method: 'moderation' },
      tokensInput: 4,
      tokensOutput: 0,
    });
  }
}
